apiVersion: v1
kind: Template
metadata:
  name: alameda-crd-rbac
  annotations:
    openshift.io/display-name: "Alameda CRD & RBAC"
    description: "Alameda CRD & RBAC is used to create the general CustomResourceDefinition and the RBAC for a project"
    iconClass: "icon-openshift"
    tags: "alameda, crd, rbac"
labels:
  template: alameda-crd-rbac
  app: alameda-crd-rbac
objects:
# TODO: CustomResourceDefinition should be created by self-component in next version.
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      controller-tools.k8s.io: "1.0"
    name: alamedarecommendations.autoscaling.containers.ai
  spec:
    group: autoscaling.containers.ai
    names:
      kind: AlamedaRecommendation
      plural: alamedarecommendations
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              containers:
                items:
                  properties:
                    name:
                      type: string
                    resources:
                      type: object
                  required:
                  - name
                  type: object
                type: array
            required:
            - containers
            type: object
          status:
            type: object
    version: v1alpha1
  status:
    acceptedNames:
      kind: ""
      plural: ""
    conditions: []
    storedVersions: []
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:    
    labels:
      controller-tools.k8s.io: "1.0"
    name: alamedascalers.autoscaling.containers.ai
  spec:
    group: autoscaling.containers.ai
    names:
      kind: AlamedaScaler
      plural: alamedascalers
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: >-
              'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: >-
              'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              customResourceVersion:
                type: string
              enableexecution:
                type: boolean
              policy:
                enum:
                - stable
                - compact
                type: string
              scalingTools:
                items:
                  enum:
                  - vpa
                  - hpa
                  type: string
                type: array
              selector:
                description: 'Important: Run "make" to regenerate code after modifying this file'
                type: object
            required:
            - selector
            type: object
          status:
            properties:
              alamedaController:
                properties:
                  deploymentconfigs:
                    type: object
                  deployments:
                    type: object
                type: object
            type: object
    version: v1alpha1
  status:
    acceptedNames:
      kind: ""
      plural: ""
    conditions: []
    storedVersions: []
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: "alameda-datahub-${PROJECT_NAME}"
  rules:
  # Permission for query prometheus under namespace openshift-monitoring 
  - apiGroups: 
    - ""
    resources: 
    - namespaces
    verbs: 
    - get
  - apiGroups:
    - autoscaling.containers.ai
    resources:
    - alamedarecommendations
    verbs:
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    name: "alameda-operator-${PROJECT_NAME}"
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - pods
    - replicationcontrollers
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - replicasets
    - deployments
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - apps.openshift.io
    resources:
    - deploymentconfigs
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - autoscaling.containers.ai
    resources:
    - alamedascalers
    - alamedarecommendations
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - autoscaling.containers.ai
    resources:
    - alamedascalers/finalizers
    verbs:
    - update
  # Permission for query prometheus under namespace openshift-monitoring 
  - apiGroups: 
    - ""
    resources: 
    - namespaces
    verbs: 
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: "alameda-datahub-${PROJECT_NAME}"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "alameda-datahub-${PROJECT_NAME}"
  subjects:
  - kind: ServiceAccount
    name: alameda-datahub
    namespace: "${PROJECT_NAME}"
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: "alameda-operator-${PROJECT_NAME}"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "alameda-operator-${PROJECT_NAME}"
  subjects:
  - kind: ServiceAccount
    name: alameda-operator
    namespace: "${PROJECT_NAME}"
parameters:
- name: PROJECT_NAME
  displayName: alameda-dev namespace
  description: The project name assigned to the ServiceAccount.
  required: true
  value: ""
